package com.sevenbee.mailCONSTANT;

public class mail_CONSTANT {

	public String mail_VERIFY(String name , String OTP) {
		
		String body = "<head>\r\n"
				+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        body {\r\n"
				+ "            margin: 0;\r\n"
				+ "            background: #FEFEFE;\r\n"
				+ "            color: #585858;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table {\r\n"
				+ "            font-size: 15px;\r\n"
				+ "            line-height: 23px;\r\n"
				+ "            max-width: 500px;\r\n"
				+ "            min-width: 460px;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .table_inner {\r\n"
				+ "            min-width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        td {\r\n"
				+ "            font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "            vertical-align: top;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .carpool_logo {\r\n"
				+ "            margin: 30px auto;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .dummy_row {\r\n"
				+ "            padding-top: 20px !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .section,\r\n"
				+ "        .sectionlike {\r\n"
				+ "            background: #C9F9E9;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .section {\r\n"
				+ "            padding: 0 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .sectionlike {\r\n"
				+ "            padding-bottom: 10px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .section_content {\r\n"
				+ "            width: 100%;\r\n"
				+ "            background: #fff;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .section_content_padded {\r\n"
				+ "            padding: 0 35px 40px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .section_zag {\r\n"
				+ "            background: #F4FBF9;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .imageless_section {\r\n"
				+ "            padding-bottom: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            display: block;\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .img_section {\r\n"
				+ "            width: 100%;\r\n"
				+ "            max-width: 500px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .img_section_side_table {\r\n"
				+ "            width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        h1 {\r\n"
				+ "            font-size: 20px;\r\n"
				+ "            font-weight: 500;\r\n"
				+ "            margin-top: 40px;\r\n"
				+ "            margin-bottom: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .near_title {\r\n"
				+ "            margin-top: 10px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .last {\r\n"
				+ "            margin-bottom: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a {\r\n"
				+ "            color: #63D3CD;\r\n"
				+ "            font-weight: 500;\r\n"
				+ "            word-break: break-word;\r\n"
				+ "            /* Footer has long unsubscribe link */\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .button {\r\n"
				+ "            display: block;\r\n"
				+ "            width: 100%;\r\n"
				+ "            max-width: 300px;\r\n"
				+ "            background: #20DA9C;\r\n"
				+ "            border-radius: 8px;\r\n"
				+ "            color: #fff;\r\n"
				+ "            font-size: 18px;\r\n"
				+ "            font-weight: normal;\r\n"
				+ "            /* Resetting from a */\r\n"
				+ "            padding: 12px 0;\r\n"
				+ "            margin: 30px auto 0;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        small {\r\n"
				+ "            display: block;\r\n"
				+ "            width: 100%;\r\n"
				+ "            max-width: 330px;\r\n"
				+ "            margin: 14px auto 0;\r\n"
				+ "            font-size: 14px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .signature {\r\n"
				+ "            padding: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer,\r\n"
				+ "        .footer_like {\r\n"
				+ "            background: #1FD99A;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer {\r\n"
				+ "            padding: 0 20px 30px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer_content {\r\n"
				+ "            width: 100%;\r\n"
				+ "            text-align: center;\r\n"
				+ "            font-size: 12px;\r\n"
				+ "            line-height: initial;\r\n"
				+ "            color: #005750;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer_content a {\r\n"
				+ "            color: #005750;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer_item_image {\r\n"
				+ "            margin: 0 auto 10px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer_item_caption {\r\n"
				+ "            margin: 0 auto;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .footer_legal {\r\n"
				+ "            padding: 20px 0 40px;\r\n"
				+ "            margin: 0;\r\n"
				+ "            font-size: 12px;\r\n"
				+ "            color: #A5A5A5;\r\n"
				+ "            line-height: 1.5;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .text_left {\r\n"
				+ "            text-align: left;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .text_right {\r\n"
				+ "            text-align: right;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .va {\r\n"
				+ "            vertical-align: middle;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .stats {\r\n"
				+ "            min-width: auto !important;\r\n"
				+ "            max-width: 370px;\r\n"
				+ "            margin: 30px auto 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .counter {\r\n"
				+ "            font-size: 22px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .stats_counter {\r\n"
				+ "            width: 23%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .stats_image {\r\n"
				+ "            width: 18%;\r\n"
				+ "            padding: 0 10px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .stats_meta {\r\n"
				+ "            width: 59%;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .stats_spaced {\r\n"
				+ "            padding-top: 16px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .walkthrough_spaced {\r\n"
				+ "            padding-top: 24px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .walkthrough {\r\n"
				+ "            max-width: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .walkthrough_meta {\r\n"
				+ "            padding-left: 20px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .table_checkmark {\r\n"
				+ "            padding-top: 30px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .table_checkmark_item {\r\n"
				+ "            font-size: 15px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .td_checkmark {\r\n"
				+ "            width: 24px;\r\n"
				+ "            padding: 7px 12px 0 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .padded_bottom {\r\n"
				+ "            padding-bottom: 40px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .marginless {\r\n"
				+ "            margin: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* Restricting responsive for iOS Mail app only as Inbox/Gmail have render bugs */\r\n"
				+ "        @media only screen and (max-width: 480px) and (-webkit-min-device-pixel-ratio: 2) {\r\n"
				+ "            table {\r\n"
				+ "                min-width: auto !important;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .section_content_padded {\r\n"
				+ "                padding-right: 25px !important;\r\n"
				+ "                padding-left: 25px !important;\r\n"
				+ "            }\r\n"
				+ "\r\n"
				+ "            .counter {\r\n"
				+ "                font-size: 18px !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"	margin: 0;\r\n"
				+ "	background: #FEFEFE;\r\n"
				+ "	color: #585858;\r\n"
				+ "\">\r\n"
				+ "    <!-- Preivew text -->\r\n"
				+ "    <span class=\"preheader\"\r\n"
				+ "        style=\"display: none !important; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;border-collapse: collapse;border: 0px;\"></span>\r\n"
				+ "    <!-- Carpool logo -->\r\n"
				+ "    <table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"	font-size: 15px;\r\n"
				+ "	line-height: 23px;\r\n"
				+ "	max-width: 500px;\r\n"
				+ "	min-width: 460px;\r\n"
				+ "	text-align: center;\r\n"
				+ "\">\r\n"
				+ "        <tbody>\r\n"
				+ "            <tr>\r\n"
				+ "                <td style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "\">\r\n"
				+ "                    <img src=\"https://scontent.fsgn2-7.fna.fbcdn.net/v/t39.30808-6/330314836_746923423560052_2375696856074264193_n.png?stp=dst-png_s960x960&_nc_cat=109&ccb=1-7&_nc_sid=e3f864&_nc_ohc=VV_H7QnjekEAX_vRD-u&_nc_ht=scontent.fsgn2-7.fna&oh=00_AfBONJKJm8PXM_WzbeEG9bdiURiS2AACKovfGd9enLHwaw&oe=63F105F6\"\r\n"
				+ "                        class=\"carpool_logo\" width=\"450\" style=\"	display: block;\r\n"
				+ "	margin: 0 auto;\r\n"
				+ "margin: 30px auto;\">\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "            <!-- Header -->\r\n"
				+ "            <tr>\r\n"
				+ "                <td class=\"sectionlike imageless_section\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "  background: #f9f8c9;\r\n"
				+ "  padding-bottom: 10px;\r\n"
				+ "padding-bottom: 20px;\"></td>\r\n"
				+ "            </tr>\r\n"
				+ "            <!-- Content -->\r\n"
				+ "            <tr>\r\n"
				+ "                <td class=\"section\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "	background: #f9f8c9;\r\n"
				+ "	padding: 0 20px;\r\n"
				+ "\">\r\n"
				+ "                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"section_content\" style=\"	font-size: 15px;\r\n"
				+ "	line-height: 23px;\r\n"
				+ "	max-width: 500px;\r\n"
				+ "	min-width: 460px;\r\n"
				+ "	text-align: center;\r\n"
				+ "	width: 100%;\r\n"
				+ "	background: #fff;\r\n"
				+ "\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td class=\"section_content_padded\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "padding: 0 35px 40px;\">\r\n"
				+ "                                    <h1 style=\"	font-size: 20px;\r\n"
				+ "	font-weight: 500;\r\n"
				+ "	margin-top: 40px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "\">Hi "+ name +" ,</h1>\r\n"
				+ "                                    <p class=\"near_title last\" style=\"margin-top: 10px;margin-bottom: 0;\">Vui lòng xác\r\n"
				+ "                                        minh rằng địa chỉ email của bạn bằng mã OTP bên dưới.</p>\r\n"
				+ "                                    <h3 style=\"	display: block;\r\n"
				+ "	width: 100%;\r\n"
				+ "	max-width: 300px;\r\n"
				+ "	background: #EBB000;\r\n"
				+ "	border-radius: 8px;\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 18px;\r\n"
				+ "	padding: 12px 0;\r\n"
				+ "	margin: 30px auto 0;\r\n"
				+ "	text-decoration: none;\r\n"
				+ "\" target=\"_blank\">"+ OTP +"</h3>\r\n"
				+ "\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "            <!-- Signature -->\r\n"
				+ "            <tr>\r\n"
				+ "                <td class=\"section\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "	background: #f9f8c9;\r\n"
				+ "	padding: 0 20px;\r\n"
				+ "\">\r\n"
				+ "                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"section_content section_zag\" style=\"	font-size: 15px;\r\n"
				+ "	line-height: 23px;\r\n"
				+ "	max-width: 500px;\r\n"
				+ "	min-width: 460px;\r\n"
				+ "	text-align: center;\r\n"
				+ "	width: 100%;\r\n"
				+ "	background: #fff;\r\n"
				+ "background: #F4FBF9;\">\r\n"
				+ "                        <tbody>\r\n"
				+ "                            <tr>\r\n"
				+ "                                <td class=\"signature\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "padding: 20px;\">\r\n"
				+ "                                    <p class=\"marginless\" style=\"margin: 0;\">Have a nice day, <br>Seven Bee Team\r\n"
				+ "                                    </p>\r\n"
				+ "                                </td>\r\n"
				+ "                            </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                    </table>\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "            <!-- Footer -->\r\n"
				+ "            <tr>\r\n"
				+ "                <td class=\"section dummy_row\" style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "	background: #f9f8c9;\r\n"
				+ "	padding: 0 20px;\r\n"
				+ "padding-top: 20px !important;\"></td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "                <td style=\"	font-family: -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\r\n"
				+ "	vertical-align: top;\r\n"
				+ "    border: none !important;\r\n"
				+ "\">\r\n"
				+ "                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"section_content\" style=\"	font-size: 15px;\r\n"
				+ "	line-height: 23px;\r\n"
				+ "	max-width: 500px;\r\n"
				+ "	min-width: 460px;\r\n"
				+ "	text-align: center;\r\n"
				+ "	width: 100%;\r\n"
				+ "	background: #fff;\r\n"
				+ "\">\r\n"
				+ "\r\n"
				+ "                    </table>\r\n"
				+ "\r\n"
				+ "</body>";
		return body;
	}
	
}
